### ISSUE TITLE
Go 1.10 incompatibility

### ISSUE THREAD

**Issue by aeriff** [tumblr/go-collins#14]
Hi,

Due to change https://github.com/golang/go/issues/21353 (report: https://github.com/golang/go/issues/21357), calling `json.Unmarshal` on anything containing a `collins.Response` struct will fail when built with Go 1.10 due to the private `container` field containing an unexported struct: https://github.com/tumblr/go-collins/blob/master/collins/collins.go#L65-L74

For now I have a local workaround, but I will defer to the maintainers on how to deal with this (either export the object, or remove it altogether as it doesn't seem to be used anywhere internally once set: https://github.com/tumblr/go-collins/blob/master/collins/collins.go#L267-L275).

**Comment by defect** [comment]
The fix i had in mind was just exporting it. Something like this:
```
diff --git a/collins/collins.go b/collins/collins.go
index f31ad6d..df46d31 100644
--- a/collins/collins.go
+++ b/collins/collins.go
@@ -53,7 +53,7 @@ type Error struct {
        } `json:"data"`
 }

-type container struct {
+type Container struct {
        CollinsStatus string      `json:"status"`
        Data          interface{} `json:"data"`
 }
@@ -65,7 +65,7 @@ type container struct {
 type Response struct {
        *http.Response

-       *container
+       *Container

        PreviousPage int
        CurrentPage  int
@@ -269,7 +269,7 @@ func (c *Client) Do(req *http.Request, v interface{}) (*Response, error) {
        // It also allows accessing `response.container.Status` etc. to get helpful
        // response info from Collins.
        if v != nil {
-               response.container = &container{
+               response.Container = &Container{
                        Data: v,
                }
        }
```

I think that is how they solved it in go-github (which go-collins is influenced by).

@byxorna @roymarantz Any other ideas? I'll play around a bit to see if we can actually remove the container somehow.

**Comment by byxorna** [comment]
@defect we totally should use exported structs. I am actually surprised this worked in go <= 1.9.
