### ISSUE TITLE
Cannot Update lshw and lldp using 

### ISSUE THREAD

**Issue by laltomar** [tumblr/go-collins#26]
I am getting the following error while invoking the Update method of the AssetService struct.

go run main.go update-asset 3d439b49-20ab-4a43-b128-85d1e63e6463 "$(cat lshw.xml)" "$(cat lldp.txt)"
Error Updating Asset: Response with unexpected Content-Type - `' received.
panic: Response with unexpected Content-Type - `' received.

Below is the code used to invoke the method.

		opts := collins.AssetUpdateOpts{
			Lshw:       args[1],
			Lldp:       args[2],
			ChassisTag: "Chasis 123",
		}

		_, err := client.Assets.Update(assetName, &opts)
		if err != nil {
			fmt.Println(fmt.Errorf("Error Updating Asset: %s", err))
			panic(err)
		}
[lldp.txt](https://github.com/tumblr/go-collins/files/3091352/lldp.txt)

**Comment by laltomar** [comment]
[lshw.xml.txt](https://github.com/tumblr/go-collins/files/3091524/lshw.xml.txt)

**Comment by defect** [comment]
Thanks for the issue! I haven't been able to try it out for myself yet, but do you have any more information on what data you're receiving back from the collins API? Or maybe logs from collins itself? 

I'll try to get some time to dig in this week, but any additional information would be helpful!
