### ISSUE TITLE
Argument "action" in PowerManagment calls miscapitalized

### ISSUE THREAD

**Issue by CaptainYANG** [tumblr/go-collins#7]
Calling client.Management.PowerOn(tag) return 400 bad request error.
The request is POST /api/asset/{assetTag}/power?Action=powerOn HTTP/1.1\r\n, while the `Action` should be `action`.
Change
https://github.com/tumblr/go-collins/blob/master/collins/management.go#L29 to 
```
Action string `url:"action"`
```
to fix it.

**Comment by defect** [comment]
NIce catch, thank you! I've opened a quick PR to have it fixed.
